"""empty message

Revision ID: 99c78fa559ea
Revises: fa12ad3a26c2
Create Date: 2021-05-24 20:17:19.526562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99c78fa559ea'
down_revision = 'fa12ad3a26c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observationer', sa.Column('lokal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'observationer', 'lokaler', ['lokal_id'], ['id'])
    op.drop_column('observationer', 'plats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observationer', sa.Column('plats', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'observationer', type_='foreignkey')
    op.drop_column('observationer', 'lokal_id')
    # ### end Alembic commands ###
